### ISSUE TITLE
package-info.java being annotated

### ISSUE THREAD

**Issue by Cyborgmas** [MinecraftForge/MergeTool#2]
With mojang now including the `package-info.java` files, merge tool is seeing them being present in the client jar but not in the server jar and annotating them, but it's not compilable.

**Comment by LexManos** [comment]
Interesting, I've only poked some of the tools so far. I haven't looked at the code too much. But the question is... why arnt the package infos on the server. Is it just client/rendering classes? Should we make @OnlyIn available as a package annotation or should we special case this?

Just thinking. Opinions?

**Comment by Cyborgmas** [comment]
Yeah it is just client packages I meant, they are present on both when the packages are present on both.

**Comment by zml2008** [comment]
There are client-only packages, but no server-only packages at the moment. imo the most sensible way to resolve this is to just make `@OnlyIn` applicable to packages as well, with some javadoc indicating that applying it to a package indicates that the package-info itself is sided, not necessarily the package.

While a package-info being sided almost certainly implies that the package itself is sided, it's still good to make that distinction clear

**Comment by LexManos** [comment]
Ya I think the best option is to just extend the annotation. You're correct the file being sided probably means the rest of the package is sided. But that's not guaranteed. So we will document it as "This ONLY means the package-info class is sided. The associated package may or may not be sided, refer to the individual classes"

I'm driving home from Memorial day shinnagins today, so I'll look into this tomarrow.

**Comment by LexManos** [comment]
Closed by https://github.com/MinecraftForge/MergeTool/pull/3
